//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.sf.ws.Timbrado
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", ConfigurationName="com.sf.ws.Timbrado.TimbradoPortType")]
    public interface TimbradoPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:cancelarPorNotaCredito", ReplyAction="urn:cancelarPorNotaCreditoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarPorNotaCreditoResponse> cancelarPorNotaCreditoAsync(com.sf.ws.Timbrado.cancelarPorNotaCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:cancelarViaCSDAlmacenado", ReplyAction="urn:cancelarViaCSDAlmacenadoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoResponse> cancelarViaCSDAlmacenadoAsync(com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:enviarSolicitudCancelacion", ReplyAction="urn:enviarSolicitudCancelacionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.enviarSolicitudCancelacionResponse> enviarSolicitudCancelacionAsync(com.sf.ws.Timbrado.enviarSolicitudCancelacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:cancelar", ReplyAction="urn:cancelarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarResponse> cancelarAsync(com.sf.ws.Timbrado.cancelarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:timbrarBase64", ReplyAction="urn:timbrarBase64Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.timbrarBase64Response> timbrarBase64Async(com.sf.ws.Timbrado.timbrarBase64Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:timbrar", ReplyAction="urn:timbrarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.timbrarResponse> timbrarAsync(com.sf.ws.Timbrado.timbrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:cancelarBase64", ReplyAction="urn:cancelarBase64Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarBase64Response> cancelarBase64Async(com.sf.ws.Timbrado.cancelarBase64Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDIResultadoCertificacion
    {
        
        private string cadenaOriginalField;
        
        private string certificadoSATField;
        
        private byte[] cfdiTimbradoField;
        
        private System.Nullable<System.DateTime> fechaTimbradoField;
        
        private bool fechaTimbradoFieldSpecified;
        
        private string mensajeField;
        
        private byte[] qrCodeField;
        
        private string selloSATField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private string uuidField;
        
        private string versionTFDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cadenaOriginal
        {
            get
            {
                return this.cadenaOriginalField;
            }
            set
            {
                this.cadenaOriginalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string certificadoSAT
        {
            get
            {
                return this.certificadoSATField;
            }
            set
            {
                this.certificadoSATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=2)]
        public byte[] cfdiTimbrado
        {
            get
            {
                return this.cfdiTimbradoField;
            }
            set
            {
                this.cfdiTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> fechaTimbrado
        {
            get
            {
                return this.fechaTimbradoField;
            }
            set
            {
                this.fechaTimbradoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaTimbradoSpecified
        {
            get
            {
                return this.fechaTimbradoFieldSpecified;
            }
            set
            {
                this.fechaTimbradoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true, Order=5)]
        public byte[] qrCode
        {
            get
            {
                return this.qrCodeField;
            }
            set
            {
                this.qrCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string selloSAT
        {
            get
            {
                return this.selloSATField;
            }
            set
            {
                this.selloSATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string versionTFD
        {
            get
            {
                return this.versionTFDField;
            }
            set
            {
                this.versionTFDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDICertificacion
    {
        
        private string mensajeField;
        
        private CFDIResultadoCertificacion[] resultadosField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true, Order=1)]
        public CFDIResultadoCertificacion[] resultados
        {
            get
            {
                return this.resultadosField;
            }
            set
            {
                this.resultadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDIResultadoCancelacion
    {
        
        private string mensajeField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private string statusUUIDField;
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string statusUUID
        {
            get
            {
                return this.statusUUIDField;
            }
            set
            {
                this.statusUUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com/xsd")]
    public partial class CFDICancelacion
    {
        
        private string mensajeField;
        
        private CFDIResultadoCancelacion[] resultadosField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultados", IsNullable=true, Order=1)]
        public CFDIResultadoCancelacion[] resultados
        {
            get
            {
                return this.resultadosField;
            }
            set
            {
                this.resultadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarPorNotaCredito", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarPorNotaCreditoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] derCertCSD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] derKeyCSD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contrasenaCSD;
        
        public cancelarPorNotaCreditoRequest()
        {
        }
        
        public cancelarPorNotaCreditoRequest(string usuario, string password, string uuid, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD)
        {
            this.usuario = usuario;
            this.password = password;
            this.uuid = uuid;
            this.derCertCSD = derCertCSD;
            this.derKeyCSD = derKeyCSD;
            this.contrasenaCSD = contrasenaCSD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarPorNotaCreditoResponse", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarPorNotaCreditoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDIResultadoCertificacion @return;
        
        public cancelarPorNotaCreditoResponse()
        {
        }
        
        public cancelarPorNotaCreditoResponse(com.sf.ws.Timbrado.CFDIResultadoCertificacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarViaCSDAlmacenado", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarViaCSDAlmacenadoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rfcEmisor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)]
        public string[] uuids;
        
        public cancelarViaCSDAlmacenadoRequest()
        {
        }
        
        public cancelarViaCSDAlmacenadoRequest(string usuario, string password, string rfcEmisor, string[] uuids)
        {
            this.usuario = usuario;
            this.password = password;
            this.rfcEmisor = rfcEmisor;
            this.uuids = uuids;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarViaCSDAlmacenadoResponse", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarViaCSDAlmacenadoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDICancelacion @return;
        
        public cancelarViaCSDAlmacenadoResponse()
        {
        }
        
        public cancelarViaCSDAlmacenadoResponse(com.sf.ws.Timbrado.CFDICancelacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSolicitudCancelacion", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class enviarSolicitudCancelacionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] solicitudCancelacion;
        
        public enviarSolicitudCancelacionRequest()
        {
        }
        
        public enviarSolicitudCancelacionRequest(string usuario, string password, byte[] solicitudCancelacion)
        {
            this.usuario = usuario;
            this.password = password;
            this.solicitudCancelacion = solicitudCancelacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSolicitudCancelacionResponse", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class enviarSolicitudCancelacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDICancelacion @return;
        
        public enviarSolicitudCancelacionResponse()
        {
        }
        
        public enviarSolicitudCancelacionResponse(com.sf.ws.Timbrado.CFDICancelacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelar", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)]
        public string[] uuids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] derCertCSD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] derKeyCSD;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contrasenaCSD;
        
        public cancelarRequest()
        {
        }
        
        public cancelarRequest(string usuario, string password, string[] uuids, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD)
        {
            this.usuario = usuario;
            this.password = password;
            this.uuids = uuids;
            this.derCertCSD = derCertCSD;
            this.derKeyCSD = derKeyCSD;
            this.contrasenaCSD = contrasenaCSD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarResponse", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDICancelacion @return;
        
        public cancelarResponse()
        {
        }
        
        public cancelarResponse(com.sf.ws.Timbrado.CFDICancelacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbrarBase64", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class timbrarBase64Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string cfdiBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=3)]
        public bool zip;
        
        public timbrarBase64Request()
        {
        }
        
        public timbrarBase64Request(string usuario, string password, string cfdiBase64, bool zip)
        {
            this.usuario = usuario;
            this.password = password;
            this.cfdiBase64 = cfdiBase64;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbrarBase64Response", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class timbrarBase64Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDICertificacion @return;
        
        public timbrarBase64Response()
        {
        }
        
        public timbrarBase64Response(com.sf.ws.Timbrado.CFDICertificacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbrar", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class timbrarRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", IsNullable=true)]
        public byte[] cfdi;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=3)]
        public bool zip;
        
        public timbrarRequest()
        {
        }
        
        public timbrarRequest(string usuario, string password, byte[] cfdi, bool zip)
        {
            this.usuario = usuario;
            this.password = password;
            this.cfdi = cfdi;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="timbrarResponse", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class timbrarResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDICertificacion @return;
        
        public timbrarResponse()
        {
        }
        
        public timbrarResponse(com.sf.ws.Timbrado.CFDICertificacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarBase64", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarBase64Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("uuids", IsNullable=true)]
        public string[] uuids;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string derCertCSDBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string derKeyCSDBase64;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string contrasenaCSD;
        
        public cancelarBase64Request()
        {
        }
        
        public cancelarBase64Request(string usuario, string password, string[] uuids, string derCertCSDBase64, string derKeyCSDBase64, string contrasenaCSD)
        {
            this.usuario = usuario;
            this.password = password;
            this.uuids = uuids;
            this.derCertCSDBase64 = derCertCSDBase64;
            this.derKeyCSDBase64 = derKeyCSDBase64;
            this.contrasenaCSD = contrasenaCSD;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarBase64Response", WrapperNamespace="http://timbrado.ws.cfdi.solucionfactible.com", IsWrapped=true)]
    public partial class cancelarBase64Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://timbrado.ws.cfdi.solucionfactible.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public com.sf.ws.Timbrado.CFDICancelacion @return;
        
        public cancelarBase64Response()
        {
        }
        
        public cancelarBase64Response(com.sf.ws.Timbrado.CFDICancelacion @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface TimbradoPortTypeChannel : com.sf.ws.Timbrado.TimbradoPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TimbradoPortTypeClient : System.ServiceModel.ClientBase<com.sf.ws.Timbrado.TimbradoPortType>, com.sf.ws.Timbrado.TimbradoPortType
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TimbradoPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(TimbradoPortTypeClient.GetBindingForEndpoint(endpointConfiguration), TimbradoPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TimbradoPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TimbradoPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TimbradoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarPorNotaCreditoResponse> com.sf.ws.Timbrado.TimbradoPortType.cancelarPorNotaCreditoAsync(com.sf.ws.Timbrado.cancelarPorNotaCreditoRequest request)
        {
            return base.Channel.cancelarPorNotaCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarPorNotaCreditoResponse> cancelarPorNotaCreditoAsync(string usuario, string password, string uuid, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD)
        {
            com.sf.ws.Timbrado.cancelarPorNotaCreditoRequest inValue = new com.sf.ws.Timbrado.cancelarPorNotaCreditoRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.uuid = uuid;
            inValue.derCertCSD = derCertCSD;
            inValue.derKeyCSD = derKeyCSD;
            inValue.contrasenaCSD = contrasenaCSD;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).cancelarPorNotaCreditoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoResponse> com.sf.ws.Timbrado.TimbradoPortType.cancelarViaCSDAlmacenadoAsync(com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoRequest request)
        {
            return base.Channel.cancelarViaCSDAlmacenadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoResponse> cancelarViaCSDAlmacenadoAsync(string usuario, string password, string rfcEmisor, string[] uuids)
        {
            com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoRequest inValue = new com.sf.ws.Timbrado.cancelarViaCSDAlmacenadoRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.rfcEmisor = rfcEmisor;
            inValue.uuids = uuids;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).cancelarViaCSDAlmacenadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.enviarSolicitudCancelacionResponse> com.sf.ws.Timbrado.TimbradoPortType.enviarSolicitudCancelacionAsync(com.sf.ws.Timbrado.enviarSolicitudCancelacionRequest request)
        {
            return base.Channel.enviarSolicitudCancelacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.enviarSolicitudCancelacionResponse> enviarSolicitudCancelacionAsync(string usuario, string password, byte[] solicitudCancelacion)
        {
            com.sf.ws.Timbrado.enviarSolicitudCancelacionRequest inValue = new com.sf.ws.Timbrado.enviarSolicitudCancelacionRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.solicitudCancelacion = solicitudCancelacion;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).enviarSolicitudCancelacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarResponse> com.sf.ws.Timbrado.TimbradoPortType.cancelarAsync(com.sf.ws.Timbrado.cancelarRequest request)
        {
            return base.Channel.cancelarAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarResponse> cancelarAsync(string usuario, string password, string[] uuids, byte[] derCertCSD, byte[] derKeyCSD, string contrasenaCSD)
        {
            com.sf.ws.Timbrado.cancelarRequest inValue = new com.sf.ws.Timbrado.cancelarRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.uuids = uuids;
            inValue.derCertCSD = derCertCSD;
            inValue.derKeyCSD = derKeyCSD;
            inValue.contrasenaCSD = contrasenaCSD;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).cancelarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.timbrarBase64Response> com.sf.ws.Timbrado.TimbradoPortType.timbrarBase64Async(com.sf.ws.Timbrado.timbrarBase64Request request)
        {
            return base.Channel.timbrarBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.timbrarBase64Response> timbrarBase64Async(string usuario, string password, string cfdiBase64, bool zip)
        {
            com.sf.ws.Timbrado.timbrarBase64Request inValue = new com.sf.ws.Timbrado.timbrarBase64Request();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfdiBase64 = cfdiBase64;
            inValue.zip = zip;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).timbrarBase64Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.timbrarResponse> com.sf.ws.Timbrado.TimbradoPortType.timbrarAsync(com.sf.ws.Timbrado.timbrarRequest request)
        {
            return base.Channel.timbrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.timbrarResponse> timbrarAsync(string usuario, string password, byte[] cfdi, bool zip)
        {
            com.sf.ws.Timbrado.timbrarRequest inValue = new com.sf.ws.Timbrado.timbrarRequest();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.cfdi = cfdi;
            inValue.zip = zip;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).timbrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarBase64Response> com.sf.ws.Timbrado.TimbradoPortType.cancelarBase64Async(com.sf.ws.Timbrado.cancelarBase64Request request)
        {
            return base.Channel.cancelarBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<com.sf.ws.Timbrado.cancelarBase64Response> cancelarBase64Async(string usuario, string password, string[] uuids, string derCertCSDBase64, string derKeyCSDBase64, string contrasenaCSD)
        {
            com.sf.ws.Timbrado.cancelarBase64Request inValue = new com.sf.ws.Timbrado.cancelarBase64Request();
            inValue.usuario = usuario;
            inValue.password = password;
            inValue.uuids = uuids;
            inValue.derCertCSDBase64 = derCertCSDBase64;
            inValue.derKeyCSDBase64 = derKeyCSDBase64;
            inValue.contrasenaCSD = contrasenaCSD;
            return ((com.sf.ws.Timbrado.TimbradoPortType)(this)).cancelarBase64Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TimbradoHttpsSoap11Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TimbradoHttpsSoap12Endpoint))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TimbradoHttpsSoap11Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://solucionfactible.com/ws/services/Timbrado.TimbradoHttpsSoap11Endpoint/");
            }
            if ((endpointConfiguration == EndpointConfiguration.TimbradoHttpsSoap12Endpoint))
            {
               return new System.ServiceModel.EndpointAddress("https://testing.solucionfactible.com/ws/services/Timbrado.TimbradoHttpsSoap12Endpoint/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {           
            TimbradoHttpsSoap11Endpoint,
            
            TimbradoHttpsSoap12Endpoint,
        }
    }
}
